/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendCliente;

/**
 *
 * @author phily
 */
public class IngresoPedido extends javax.swing.JDialog {
    int codigoPedido;
    
    /**
     * Creates new form IngresoPedido
     */
    public IngresoPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_codigoPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        txt_codigoPedido.setFont(new java.awt.Font("Sawasdee", 1, 19)); // NOI18N
        txt_codigoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoPedidoActionPerformed(evt);
            }
        });
        txt_codigoPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoPedidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoPedidoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_codigoPedido);
        txt_codigoPedido.setBounds(110, 80, 350, 60);

        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel2.setText("INGRESA EL CÓDIGO DEL PEDIDO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 350, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoPedidoActionPerformed
        
    }//GEN-LAST:event_txt_codigoPedidoActionPerformed

    private void txt_codigoPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoPedidoKeyPressed
        codigoPedido=Integer.parseInt(txt_codigoPedido.getText());
    }//GEN-LAST:event_txt_codigoPedidoKeyPressed

    private void txt_codigoPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoPedidoKeyTyped
        if((evt.getKeyChar()<=48 || evt.getKeyChar()>=90)){
                evt.consume();
         }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoPedidoKeyTyped

    public int retornarCodigo(){
        return codigoPedido;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_codigoPedido;
    // End of variables declaration//GEN-END:variables
}
