/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

/**
 *
 * @author phily
 */
public class avisoDBvacia extends javax.swing.JDialog {
    boolean presionado=false;
    
    
    /**
     * Creates new form avisoDBvacia
     * @param parent
     * @param modal
     */
    public avisoDBvacia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_aviso = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        lbl_mensaje = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(504, 272));
        setMinimumSize(new java.awt.Dimension(504, 272));
        setPreferredSize(new java.awt.Dimension(504, 272));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_aviso.setBackground(new java.awt.Color(234, 184, 84));
        lbl_aviso.setFont(new java.awt.Font("Sawasdee", 1, 19)); // NOI18N
        lbl_aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_aviso.setText("--LA BASE DE DATOS SE ENCUENTRA VACÍA--");
        lbl_aviso.setOpaque(true);
        getContentPane().add(lbl_aviso);
        lbl_aviso.setBounds(0, 30, 510, 50);

        btn_aceptar.setFont(new java.awt.Font("Sawasdee", 1, 19)); // NOI18N
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.setMaximumSize(new java.awt.Dimension(95, 75));
        btn_aceptar.setMinimumSize(new java.awt.Dimension(95, 75));
        btn_aceptar.setPreferredSize(new java.awt.Dimension(95, 75));
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar);
        btn_aceptar.setBounds(180, 180, 130, 50);

        lbl_mensaje.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        lbl_mensaje.setForeground(new java.awt.Color(220, 211, 211));
        lbl_mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mensaje.setText("Por favor presione aceptar para abastecer a la base de datos");
        getContentPane().add(lbl_mensaje);
        lbl_mensaje.setBounds(0, 100, 500, 50);

        lbl_Fondo.setBackground(new java.awt.Color(100, 105, 106));
        lbl_Fondo.setOpaque(true);
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 510, 252);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        presionado=true;
        
        this.dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

     public boolean devolverDecision(){
      return presionado;
    }            
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JLabel lbl_mensaje;
    // End of variables declaration//GEN-END:variables
}
