/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

/**
 *
 * @author phily
 */
public class Home extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbBx_sucursales = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtn_modoGerente = new javax.swing.JRadioButton();
        rbtn_modoCajero = new javax.swing.JRadioButton();
        rbtn_modoBodeguero = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtF_nombreUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 747));
        setMinimumSize(new java.awt.Dimension(1000, 747));
        setPreferredSize(new java.awt.Dimension(1000, 747));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(139, 124, 109));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 225, 225));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<< WORKspace >>");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 1000, 60);

        cbBx_sucursales.setFont(new java.awt.Font("Samanata", 0, 15)); // NOI18N
        cbBx_sucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBx_sucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBx_sucursalesActionPerformed(evt);
            }
        });
        getContentPane().add(cbBx_sucursales);
        cbBx_sucursales.setBounds(110, 210, 320, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos_Clientes_GT_Intelaf.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 600, 340, 100);

        jLabel3.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel3.setText("TIENDA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 170, 150, 35);

        jLabel4.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel4.setText("CARGO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 280, 100, 35);

        buttonGroup1.add(rbtn_modoGerente);
        rbtn_modoGerente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rbtn_modoGerente.setSelected(true);
        rbtn_modoGerente.setText("Gerente");
        rbtn_modoGerente.setContentAreaFilled(false);
        getContentPane().add(rbtn_modoGerente);
        rbtn_modoGerente.setBounds(140, 350, 230, 25);

        buttonGroup1.add(rbtn_modoCajero);
        rbtn_modoCajero.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rbtn_modoCajero.setText("Cajero");
        rbtn_modoCajero.setContentAreaFilled(false);
        getContentPane().add(rbtn_modoCajero);
        rbtn_modoCajero.setBounds(140, 400, 78, 25);

        buttonGroup1.add(rbtn_modoBodeguero);
        rbtn_modoBodeguero.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rbtn_modoBodeguero.setText("Bodeguero");
        rbtn_modoBodeguero.setContentAreaFilled(false);
        getContentPane().add(rbtn_modoBodeguero);
        rbtn_modoBodeguero.setBounds(140, 450, 118, 25);

        jPanel1.setBackground(new java.awt.Color(199, 116, 33));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Experiencia-Usuario.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 30, 250, 250);

        jLabel6.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel6.setText("Nombre de usuario:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 340, 190, 35);

        txtF_nombreUsuario.setFont(new java.awt.Font("Sahadeva", 0, 15)); // NOI18N
        jPanel1.add(txtF_nombreUsuario);
        txtF_nombreUsuario.setBounds(210, 340, 150, 30);

        jLabel7.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 400, 120, 35);

        btn_entrar.setFont(new java.awt.Font("Sawasdee", 1, 25)); // NOI18N
        btn_entrar.setText("ENTRAR");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_entrar);
        btn_entrar.setBounds(130, 470, 140, 50);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(150, 400, 210, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(570, 140, 380, 540);

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoPrinciapal.jpg"))); // NOI18N
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 1000, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBx_sucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBx_sucursalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBx_sucursalesActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        if(rbtn_modoCajero.isSelected()){
             ModoCajero cajero = new ModoCajero();
        
            this.dispose();
        
            cajero.setLocationRelativeTo(null);
            cajero.setVisible(true);
        }
        
        if(rbtn_modoGerente.isSelected()){
            ModoGerente gerente = new ModoGerente();
            
            this.dispose();
            
            gerente.setLocationRelativeTo(null);
            gerente.setVisible(true);
        }                     

        
    }//GEN-LAST:event_btn_entrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbBx_sucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JRadioButton rbtn_modoBodeguero;
    private javax.swing.JRadioButton rbtn_modoCajero;
    private javax.swing.JRadioButton rbtn_modoGerente;
    private javax.swing.JTextField txtF_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
