/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

import ManejoDeInformacion.ListaEnlazada;
import ManejoDeInformacion.Nodo;

/**
 *
 * @author phily
 */
public class listadoLineasErradas extends javax.swing.JDialog {

    /**
     * Creates new form listadoLineasErradas
     */
    public listadoLineasErradas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_listado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 790));
        setMinimumSize(new java.awt.Dimension(650, 790));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(650, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(149, 137, 125));
        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 23)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<<LINEAS ERRADAS>>");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 660, 30);

        txtA_listado.setEditable(false);
        txtA_listado.setColumns(20);
        txtA_listado.setFont(new java.awt.Font("Sawasdee", 0, 17)); // NOI18N
        txtA_listado.setRows(5);
        jScrollPane1.setViewportView(txtA_listado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 590, 590);

        jLabel1.setBackground(new java.awt.Color(154, 147, 139));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 219, 208));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-> Las siguientes no han logrado leerse por  sintaxis incorrecta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 640, 18);

        lbl_Fondo.setBackground(new java.awt.Color(23, 11, 11));
        lbl_Fondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector-black-polygonal-mosaic-background-creative-design-templates.jpg"))); // NOI18N
        lbl_Fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_Fondo.setOpaque(true);
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 660, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDatos(ListaEnlazada<String> listaErrada, boolean agregarNumeroLinea){//este listado de líneas sería para indicar la linea del archivo donde se encontró el error
        if(agregarNumeroLinea==true){
            mostrarDatosNumerdosAutomaticamente(listaErrada);
        }else{
            mostrarDatosConLineasDadas(listaErrada);
        }                
    }
    
    private void mostrarDatosConLineasDadas(ListaEnlazada<String> listaErrada){//Este método debe ser llamado hasta que se conozca que se ha terminado el proceso donde pueden existir errores
        Nodo<String> nodoLinea= listaErrada.obtnerPrimerNodo();
        
        txtA_listado.append("Linea     Descripción");
        
        
        for (int nodoActual = 0; nodoActual < listaErrada.darTamanio(); nodoActual++) {
            txtA_listado.append(nodoLinea.contenido+"\n");            
            
            nodoLinea=nodoLinea.nodoSiguiente;            
        }                               
    }
    
    private void mostrarDatosNumerdosAutomaticamente(ListaEnlazada<String> listaErrada){
        Nodo<String> nodoAuxiliar = listaErrada.obtnerPrimerNodo();
        
        for (int nodoActual = 0; nodoActual < listaErrada.darTamanio(); nodoActual++) {
            txtA_listado.append("[ "+ nodoActual+" ]"+"   " +nodoAuxiliar.contenido+"\n");
            
            nodoAuxiliar=nodoAuxiliar.nodoSiguiente;                        
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JTextArea txtA_listado;
    // End of variables declaration//GEN-END:variables
}
