/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

/**
 *
 * @author phily
 */
public class MenuEmergente extends javax.swing.JDialog {    
    private int transaccionAlterada;
    private int filaAfectada;
    private Listeners listener = new Listeners();
    

    /**
     * Creates new form MenuEmergente
     */
    public MenuEmergente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_eliminarTransaccionUnitaria = new javax.swing.JLabel();
        lbl_cambiarCantidadProducto = new javax.swing.JLabel();
        lbl_Framecito1 = new javax.swing.JLabel();
        lbl_Framecito2 = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_eliminarTransaccionUnitaria.setBackground(new java.awt.Color(240, 229, 217));
        lbl_eliminarTransaccionUnitaria.setFont(new java.awt.Font("Sawasdee", 1, 19)); // NOI18N
        lbl_eliminarTransaccionUnitaria.setForeground(new java.awt.Color(247, 233, 233));
        lbl_eliminarTransaccionUnitaria.setText("   Eliminar");
        lbl_eliminarTransaccionUnitaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_eliminarTransaccionUnitariaMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_eliminarTransaccionUnitaria);
        lbl_eliminarTransaccionUnitaria.setBounds(0, 50, 200, 30);

        lbl_cambiarCantidadProducto.setFont(new java.awt.Font("Sawasdee", 1, 19)); // NOI18N
        lbl_cambiarCantidadProducto.setForeground(new java.awt.Color(234, 225, 225));
        lbl_cambiarCantidadProducto.setText("   Reducir cantidad");
        lbl_cambiarCantidadProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cambiarCantidadProductoMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_cambiarCantidadProducto);
        lbl_cambiarCantidadProducto.setBounds(0, 100, 200, 33);

        lbl_Framecito1.setBackground(new java.awt.Color(245, 222, 198));
        lbl_Framecito1.setOpaque(true);
        getContentPane().add(lbl_Framecito1);
        lbl_Framecito1.setBounds(0, 18, 200, 10);

        lbl_Framecito2.setBackground(new java.awt.Color(233, 212, 191));
        lbl_Framecito2.setOpaque(true);
        getContentPane().add(lbl_Framecito2);
        lbl_Framecito2.setBounds(-1, 160, 200, 10);

        lbl_Fondo.setBackground(new java.awt.Color(98, 95, 92));
        lbl_Fondo.setOpaque(true);
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 200, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_eliminarTransaccionUnitariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eliminarTransaccionUnitariaMouseClicked
        listener.paraMousePressed(1, transaccionAlterada+1, filaAfectada+1);//tiene a ambos procesos posibles, donde termina escogiendo según la opción seleccionada y afectando al lugar[fila] clickeado           
        this.dispose();
    }//GEN-LAST:event_lbl_eliminarTransaccionUnitariaMouseClicked

    private void lbl_cambiarCantidadProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cambiarCantidadProductoMouseClicked
      
        listener.paraMousePressed(2, transaccionAlterada+1, filaAfectada+1);                
        this.dispose();        
    }//GEN-LAST:event_lbl_cambiarCantidadProductoMouseClicked

   
    
    public void definirObjetoAAfectar(int transaccionAfectada, int lugarAfectado){//Es decir la transacción a afectar...
        transaccionAlterada=transaccionAfectada;
        filaAfectada=lugarAfectado;
    }
        
    //es que para hacer esto, o eran 2 y en c/u se les definía las acciones del 
    //modelo en específico y luego se escogía a cual de las listas afectar y con 
    //elo a cual tabla de la DB afecta
    //ó
    //se hacía 1 en donde siempre se le indica cual que las cosas debe afectar...
    //y para escoger en un proceso y en otro no, para eso mejor escojo en ambos
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_Framecito1;
    private javax.swing.JLabel lbl_Framecito2;
    private javax.swing.JLabel lbl_cambiarCantidadProducto;
    private javax.swing.JLabel lbl_eliminarTransaccionUnitaria;
    // End of variables declaration//GEN-END:variables
}
