/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

/**
 *
 * @author phily
 */
public class modificadorCantidadAdquirida extends javax.swing.JDialog {
    boolean aAceptado;
    /**
     * Creates new form modificadorCantidadAdquirida
     */
    public modificadorCantidadAdquirida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spn_cantidadReducir = new javax.swing.JSpinner();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        spn_cantidadReducir.setFont(new java.awt.Font("Sawasdee", 1, 31)); // NOI18N
        spn_cantidadReducir.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(spn_cantidadReducir);
        spn_cantidadReducir.setBounds(90, 90, 170, 80);

        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar);
        btn_aceptar.setBounds(180, 200, 100, 50);

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar);
        btn_cancelar.setBounds(60, 200, 100, 50);

        jLabel1.setBackground(new java.awt.Color(89, 69, 50));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 208, 208));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CANTIDAD A DISMINUIR");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 340, 40);

        lbl_Fondo.setBackground(new java.awt.Color(140, 116, 97));
        lbl_Fondo.setOpaque(true);
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 340, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        aAceptado=true;        
        this.dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        aAceptado=false;
        this.dispose();        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    public void establecerMaximo(int maximo){
        spn_cantidadReducir.setModel(new javax.swing.SpinnerNumberModel(1, 1,maximo, 1));
    }    
    
    public boolean devolverSeleccion(){
        //pues solamente si presiona aceptar se trabajará...        
        return aAceptado;
    }
    
    public int devolverCantidadReducida(){
        return (Integer)spn_cantidadReducir.getValue();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JSpinner spn_cantidadReducir;
    // End of variables declaration//GEN-END:variables
}
