/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

/**
 *
 * @author phily
 */
public class ModoCajero extends javax.swing.JFrame {

    /**
     * Creates new form ModoCajero
     */
    public ModoCajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtn_tipoBusqueda = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_productoSeleccionado = new javax.swing.JTextField();
        spn_Cantidad = new javax.swing.JSpinner();
        rbt_productos = new javax.swing.JRadioButton();
        rbtn_pedidos = new javax.swing.JRadioButton();
        lbl_FondoIzq = new javax.swing.JLabel();
        lbl_FondoDer = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1247, 1082));
        setMinimumSize(new java.awt.Dimension(1247, 1082));
        setPreferredSize(new java.awt.Dimension(1247, 1082));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 30, 210, 20);

        jLabel4.setBackground(new java.awt.Color(217, 180, 169));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 30, 210, 20);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 60, 0, 0);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 50, 60, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 130, 190, 28);

        jLabel6.setBackground(new java.awt.Color(226, 187, 131));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 70, 170, 20);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 190, 560, 370);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1294762.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 640, 120, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sobre.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 930, 60, 50);

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoHome.png"))); // NOI18N
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_home);
        lbl_home.setBounds(470, 900, 100, 100);

        jLabel10.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel10.setText("CÓDIGO:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 130, 90, 30);

        jButton1.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jButton1.setText("ACEPTAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(1070, 940, 130, 40);
        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(660, 70, 550, 370);
        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(660, 520, 550, 390);

        jLabel11.setFont(new java.awt.Font("Sawasdee", 1, 25)); // NOI18N
        jLabel11.setText("<<VENTAS>>");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(860, 10, 160, 40);

        jLabel12.setFont(new java.awt.Font("Sawasdee", 1, 25)); // NOI18N
        jLabel12.setText("<<PEDIDOS>>");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(860, 460, 170, 43);
        getContentPane().add(txt_productoSeleccionado);
        txt_productoSeleccionado.setBounds(120, 580, 470, 28);

        spn_Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(spn_Cantidad);
        spn_Cantidad.setBounds(30, 580, 80, 28);

        groupBtn_tipoBusqueda.add(rbt_productos);
        rbt_productos.setFont(new java.awt.Font("Sawasdee", 0, 19)); // NOI18N
        rbt_productos.setText("Productos");
        getContentPane().add(rbt_productos);
        rbt_productos.setBounds(40, 950, 130, 35);

        groupBtn_tipoBusqueda.add(rbtn_pedidos);
        rbtn_pedidos.setFont(new java.awt.Font("Sawasdee", 0, 19)); // NOI18N
        rbtn_pedidos.setText("Pedidos Listos");
        getContentPane().add(rbtn_pedidos);
        rbtn_pedidos.setBounds(180, 950, 160, 35);

        lbl_FondoIzq.setBackground(new java.awt.Color(196, 64, 45));
        lbl_FondoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-mosaico-abstracto-fondo-geometrico-triangulo-elementos-diseno-ejemplo-vector-amarillo-naranja-rojo_1151-360.jpg"))); // NOI18N
        lbl_FondoIzq.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_FondoIzq.setOpaque(true);
        getContentPane().add(lbl_FondoIzq);
        lbl_FondoIzq.setBounds(0, 0, 620, 1020);

        lbl_FondoDer.setBackground(new java.awt.Color(217, 197, 115));
        lbl_FondoDer.setOpaque(true);
        getContentPane().add(lbl_FondoDer);
        lbl_FondoDer.setBounds(620, 0, 630, 1020);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        Home home = new Home();
        home.setLocationRelativeTo(null);
        
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_lbl_homeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup groupBtn_tipoBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_FondoDer;
    private javax.swing.JLabel lbl_FondoIzq;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JRadioButton rbt_productos;
    private javax.swing.JRadioButton rbtn_pedidos;
    private javax.swing.JSpinner spn_Cantidad;
    private javax.swing.JTextField txt_productoSeleccionado;
    // End of variables declaration//GEN-END:variables
}
