/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

import BackendEntidades.Trabajador;
import ManejoDeInformacion.ManejadorBusqueda;
import ManejoDeInformacion.ManejadorEstructuras;
import ManejoDeInformacion.Validador;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

    

/**
 *
 * @author phily
 */
public class nuevoProducto extends javax.swing.JFrame {
    ManejadorEstructuras estructuras = new ManejadorEstructuras();
    ManejadorBusqueda buscador = new ManejadorBusqueda();
    Validador validador = new Validador();
    private boolean esNuevoRegistro=false;
    String[] informacionIngresada = new String [7];
    
    /**
     * Creates new form nuevoProducto
     */
    public nuevoProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_fabricante = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JFormattedTextField();
        txt_precio = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_descripcion = new javax.swing.JTextArea();
        btn_agregar = new javax.swing.JButton();
        txt_garantia = new javax.swing.JFormattedTextField();
        lbl_tituloOperacion = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(618, 726));
        setMinimumSize(new java.awt.Dimension(618, 726));
        setPreferredSize(new java.awt.Dimension(618, 726));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel2.setText("CÓDIGO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 90, 20);

        jLabel3.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 90, 30);

        jLabel4.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel4.setText("CANTIDAD:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 280, 110, 30);

        jLabel5.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel5.setText("PRECIO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 240, 90, 30);

        jLabel6.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel6.setText("DESCRIPCIÓN:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 330, 140, 30);

        jLabel7.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel7.setText("GARANTÍA:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 530, 100, 30);

        jLabel9.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel9.setText("FABRICANTE:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 190, 120, 30);

        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_codigo);
        txt_codigo.setBounds(170, 90, 160, 28);

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(170, 140, 160, 28);

        txt_fabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fabricanteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_fabricante);
        txt_fabricante.setBounds(190, 190, 170, 28);

        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cantidad);
        txt_cantidad.setBounds(180, 280, 120, 28);

        txt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_precio);
        txt_precio.setBounds(150, 240, 120, 28);

        txtA_descripcion.setColumns(20);
        txtA_descripcion.setRows(5);
        txtA_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtA_descripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtA_descripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 380, 490, 120);

        btn_agregar.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar);
        btn_agregar.setBounds(450, 620, 120, 50);

        txt_garantia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+#0"))));
        txt_garantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_garantiaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_garantia);
        txt_garantia.setBounds(180, 530, 110, 28);

        lbl_tituloOperacion.setFont(new java.awt.Font("Sarai", 1, 33)); // NOI18N
        lbl_tituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloOperacion.setText("<<NUEVO PRODUCTO>>");
        getContentPane().add(lbl_tituloOperacion);
        lbl_tituloOperacion.setBounds(160, 20, 310, 40);

        lbl_Fondo.setBackground(new java.awt.Color(212, 175, 137));
        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-abstracto-geometrico-tonos-marrones_1095-35.jpg"))); // NOI18N
        lbl_Fondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_Fondo.setOpaque(true);
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 629, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String[] resultado=buscador.determinarExistenciaProducto(txt_codigo.getText());
            if(resultado!=null){//quiere decir que encontró algo...
                esNuevoRegistro=false;
                txt_codigo.setEnabled(false);
                String[] resultado2=buscador.buscarProductoEnEstaTienda(txt_codigo.getText(), Trabajador.tiendaDeTrabajo);
                mostrarDatosRegistroAnterior(recopilarDatosAnteriores(resultado, resultado2));                             
            }else{
                esNuevoRegistro=true;//puesto que voy a reutilizar ventanas debo colocar estom si no no sería necesario                
            }
        
        }
    }//GEN-LAST:event_txt_codigoKeyPressed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        recolectarInformacion();
        
        if(validador.aceptarRegistro(informacionIngresada, 3)){
            if(esNuevoRegistro){
                estructuras.insertarDatosCompletosEnProducto(informacionIngresada);
                estructuras.insertarTiendaProducto(Trabajador.tiendaDeTrabajo, informacionIngresada[0], Integer.parseInt(informacionIngresada[6]), Double.parseDouble(informacionIngresada[5]), 0, 0);
            }else{
                //llamo a los updates
                buscador.actualizarProducto(informacionIngresada);
                buscador.actualizarTiendaProducto(informacionIngresada);
            }            
            
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Hacen falta llenar campos\nobligatorios", "", JOptionPane.INFORMATION_MESSAGE);
        }    
        
        descartarRecoleccion();//independientemente de lo que suceda se debe hacer la eliminación...
        
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_garantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_garantiaKeyTyped
        if((evt.getKeyChar()<=48 || evt.getKeyChar()>=90) || txt_garantia.getText().length()>3){
            evt.consume();
        }
    }//GEN-LAST:event_txt_garantiaKeyTyped

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
       if((evt.getKeyChar()<=48 || evt.getKeyChar()>=90) || txt_cantidad.getText().length()>5){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void txt_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precioKeyTyped
       if((evt.getKeyChar()<=48 || evt.getKeyChar()>=90) || txt_precio.getText().length()>7){
            evt.consume();
        }
    }//GEN-LAST:event_txt_precioKeyTyped

    private void txt_fabricanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fabricanteKeyTyped
        if((evt.getKeyChar()>=48 && evt.getKeyChar()<=57) || txt_fabricante.getText().length()>20){
                evt.consume();
        }
    }//GEN-LAST:event_txt_fabricanteKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
         if((evt.getKeyChar()>=48 && evt.getKeyChar()<=57 )|| txt_nombre.getText().length()>19){
                evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txtA_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtA_descripcionKeyTyped
        if(txtA_descripcion.getText().length()>50){
            evt.consume();
        }
    }//GEN-LAST:event_txtA_descripcionKeyTyped

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
        if(txt_codigo.getText().length()>10){
            evt.consume();
        }
    }//GEN-LAST:event_txt_codigoKeyTyped

    public void recibirTItulo(String tituloCOrrecto){
        lbl_tituloOperacion.setText(tituloCOrrecto);
    }
    
    
    public void recolectarInformacion(){
        informacionIngresada[0]=txt_codigo.getText();
        informacionIngresada[1]=txt_nombre.getText();
        informacionIngresada[2]=txt_fabricante.getText();
        informacionIngresada[3]=txtA_descripcion.getText();
        informacionIngresada[4]=txt_garantia.getText();
        informacionIngresada[5]=txt_precio.getText();
        informacionIngresada[6]=txt_cantidad.getText();                          
    }
    
    private String[] recopilarDatosAnteriores(String resultado[], String[] resultado2){
        String[] unificado= new String[7];
        unificado[0]=resultado[0];
        unificado[1]=resultado[1];
        unificado[2]=resultado[2];
        unificado[3]=resultado[3];
        unificado[4]=resultado[4];
        unificado[5]=String.valueOf(resultado2[3]);//precio
        unificado[6]=String.valueOf(resultado2[2]);//cantidad
        
        return unificado;
    }
    
    /**
     * Encargado de recibir los datos anteriroes para que cuando desee hacer 
     * la modificación tenga algo en que basarse
     * 
     * @param datosAnteriores
     */
    public void mostrarDatosRegistroAnterior(String[] datosAnteriores){
        txt_codigo.setText(informacionIngresada[0]);
        txt_nombre.setText(informacionIngresada[1]);
        txt_fabricante.setText(informacionIngresada[2]);
        txtA_descripcion.setText(informacionIngresada[3]);
        txt_garantia.setText(informacionIngresada[4]);
        txt_precio.setText(informacionIngresada[5]);
        txt_cantidad.setText(informacionIngresada[6]);     
        
    }
    
    public void descartarRecoleccion(){
        for (int espacioActual = 0; espacioActual < informacionIngresada.length; espacioActual++) {
            informacionIngresada[espacioActual]=null;
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_tituloOperacion;
    private javax.swing.JTextArea txtA_descripcion;
    private javax.swing.JFormattedTextField txt_cantidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_fabricante;
    private javax.swing.JFormattedTextField txt_garantia;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JFormattedTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
