/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;


import BackendEntidades.Cajero;
import BackendEntidades.Gerente;
import ManejoDeInformacion.ManejadorBusqueda;
import ManejoDeInformacion.ManejadorEstructuras;
import javax.swing.JOptionPane;

/**
 *
 * @author phily
 */
public class NuevoUsuario extends javax.swing.JFrame {//solo se encarga de crear o modificar al usuario, es decir su función principal es dar un espacio para ingresar información que mandará a la DB y solo xD, si quieres obtner info de aquí, vuelve a exe otra consulta, solo que esta vez para seleccionar, en lugar de insertar...
    String[] datosUsuario= new String[7];//Se envían alamacenan los datos a registrar ya sea de cliente o trabajador, app tanto para modifs como para creaciones, lo dejo de tam 7, porque de esa manera 
    //no tendré que hacer extras con el crédito, porque cuando sea cliente el espacio que le corresponde al crédito será NULL y por ello allá en la tabla se establecerá como default 0 xD, sino sucediera así entonce solo le seteas 0 y ya :v xD JAJAJAJ además recuerda que se almacenará como string para no estarse preocupando por las conversiones...
    int tipoDialogo=0;//1-> empleado, 2-> cliente y los demás quedan en una de estas 2 categarías dependiendo de su palabra final...
    boolean esRegistroNuevo;
    ManejadorEstructuras estructuras = new ManejadorEstructuras();
    ManejadorBusqueda buscador = new ManejadorBusqueda();
    Cajero cajero = new Cajero();
    Gerente gerente = new Gerente();    
    
    /**
     * Creates new form NuevoCliente
     */
    public NuevoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloOperacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtF_Nombre = new javax.swing.JTextField();
        txtF_DPI = new javax.swing.JTextField();
        txtF_Telefono = new javax.swing.JTextField();
        FtxtF_Correo = new javax.swing.JFormattedTextField();
        txtF_Direccion = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        lbl_nitTrabajador = new javax.swing.JLabel();
        txtF_nitParaTrabajador = new javax.swing.JTextField();
        txt_codigoUsuario = new javax.swing.JTextField();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(626, 626));
        setMinimumSize(new java.awt.Dimension(626, 626));
        setPreferredSize(new java.awt.Dimension(626, 626));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_tituloOperacion.setBackground(new java.awt.Color(124, 112, 99));
        lbl_tituloOperacion.setFont(new java.awt.Font("Sawasdee", 1, 27)); // NOI18N
        lbl_tituloOperacion.setForeground(new java.awt.Color(240, 224, 224));
        lbl_tituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloOperacion.setText("NUEVO CLIENTE");
        lbl_tituloOperacion.setOpaque(true);
        getContentPane().add(lbl_tituloOperacion);
        lbl_tituloOperacion.setBounds(0, 30, 540, 30);

        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel1.setText("NIT:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 50, 35);

        jLabel3.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 140, 120, 35);

        jLabel4.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel4.setText("DPI:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 220, 50, 35);

        jLabel5.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel5.setText("No. TEL:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 180, 100, 30);

        jLabel6.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel6.setText("CORREO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 260, 91, 35);

        jLabel7.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        jLabel7.setText("DIRECCIÓN:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 300, 140, 35);

        txtF_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF_NombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtF_Nombre);
        txtF_Nombre.setBounds(190, 140, 190, 28);

        txtF_DPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF_DPIKeyTyped(evt);
            }
        });
        getContentPane().add(txtF_DPI);
        txtF_DPI.setBounds(190, 220, 150, 28);

        txtF_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF_TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtF_Telefono);
        txtF_Telefono.setBounds(190, 180, 130, 28);

        FtxtF_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FtxtF_CorreoKeyTyped(evt);
            }
        });
        getContentPane().add(FtxtF_Correo);
        FtxtF_Correo.setBounds(190, 260, 190, 28);
        getContentPane().add(txtF_Direccion);
        txtF_Direccion.setBounds(210, 300, 170, 28);

        btn_agregar.setFont(new java.awt.Font("Sawasdee", 1, 19)); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar);
        btn_agregar.setBounds(370, 390, 130, 50);

        lbl_nitTrabajador.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        lbl_nitTrabajador.setText("NIT:");
        getContentPane().add(lbl_nitTrabajador);
        lbl_nitTrabajador.setBounds(80, 340, 40, 30);

        txtF_nitParaTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF_nitParaTrabajadorKeyTyped(evt);
            }
        });
        getContentPane().add(txtF_nitParaTrabajador);
        txtF_nitParaTrabajador.setBounds(140, 340, 170, 28);

        txt_codigoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_codigoUsuario);
        txt_codigoUsuario.setBounds(90, 80, 190, 28);

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sencillo-fondo-poligonal-amarillo_1057-2586.jpg"))); // NOI18N
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 540, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoUsuarioKeyPressed
         String[] datosAnteriores;
        
         if(lbl_tituloOperacion.getText().endsWith("CLIENTE")){
             datosAnteriores=buscador.determinarExistenciaCliente(txt_codigoUsuario.getText());
         }else{//ya que no hay más opciones, de una vez un else...
             datosAnteriores=buscador.determinarExistenciaEmpleado(txt_codigoUsuario.getText());
         }
         
         if(datosAnteriores!=null){             
             //abastezco los campos con la info recibida...
             esRegistroNuevo=false;
         }else{
             esRegistroNuevo=true;
         }
    }//GEN-LAST:event_txt_codigoUsuarioKeyPressed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if(revisarCamposObligatorios()){
            //se guardan en el arreglo local los datos, para ser mandados a la DB
            //de tal manera que en el paso siguente de la pseudoFactura, puedan obtenerse
            obtnerInfoIngresada();//se guardaron los datos en el arreglo
            
            if(esRegistroNuevo){                
                registrarUsuario();//aqupi ya se escoge a cual de los 2...                
            }else{
                actualizarUsuario();
            }                        
            
            this.dispose();//lo de los booleans iba a afectar justamente a esta linea, de tal manera que si fallaba no se cerrara y aún quedara espacio para componer o intentarlo otra vez
        }else{
            JOptionPane.showMessageDialog(null, "Hacen falta llenar campos obligatorios", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_codigoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoUsuarioKeyTyped
        if(tipoDialogo==1){//quiere decir que es cliente
            if(txt_codigoUsuario.getText().length()>6){//aunque esto debe cambiar por el hecho de que los nits son de  masyoers cantidades... por ello cuando la borres deberás eliminar a las que de ella dependend, por las condiciones...
                evt.consume();            
            }
        }else{//ya que solo hay 2 ops generales...
            if((evt.getKeyChar()<=48 || evt.getKeyChar()>=90) || txt_codigoUsuario.getText().length()>7){
                evt.consume();
            }
            
        }
        
    }//GEN-LAST:event_txt_codigoUsuarioKeyTyped

    private void txtF_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_NombreKeyTyped
        if((evt.getKeyChar()>=48 && evt.getKeyChar()<=57 )|| txtF_Nombre.getText().length()>15){
                evt.consume();
        }
    }//GEN-LAST:event_txtF_NombreKeyTyped

    private void txtF_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_TelefonoKeyTyped
        if((evt.getKeyChar()<=48 || evt.getKeyChar()>=90) || txt_codigoUsuario.getText().length()>8){
                evt.consume();
         }
    }//GEN-LAST:event_txtF_TelefonoKeyTyped

    private void txtF_DPIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_DPIKeyTyped
        if((evt.getKeyChar()<=48 || evt.getKeyChar()>=90) || txt_codigoUsuario.getText().length()>13){
                evt.consume();
        }
    }//GEN-LAST:event_txtF_DPIKeyTyped

    private void FtxtF_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FtxtF_CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_FtxtF_CorreoKeyTyped

    private void txtF_nitParaTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_nitParaTrabajadorKeyTyped
        if(txt_codigoUsuario.getText().length()>6){//aunque esto debe cambiar por el hecho de que los nits son de  masyoers cantidades... por ello cuando la borres deberás eliminar a las que de ella dependend, por las condiciones...
                evt.consume();            
        }
    }//GEN-LAST:event_txtF_nitParaTrabajadorKeyTyped

    public void establecerTituloCorrecto(String tituloOperacion){
        lbl_tituloOperacion.setText(tituloOperacion);                
        
        prepararInterfazSegun();//no veo necesidad de estar recibiendo parámetros...
    }
    
    public void recibirNITnuevoCliente(String nit){
        txt_codigoUsuario.setText(nit);
    }
    
    /**
     * llamdao antes de hacer visible este diálogo, de igual manera
     * para el caso de los campos obligatorios cuando se tnega a uno
     * u otro usuario se app pero, se revisará cuando presione el 
     * btn aceptar      
     */
    private void prepararInterfazSegun(){
        if(lbl_tituloOperacion.getText().endsWith("CLIENTE")){
            txt_codigoUsuario.setEditable(false);
            lbl_nitTrabajador.setVisible(false);
            txtF_nitParaTrabajador.setVisible(false);
            tipoDialogo=1;
            
        }else{
            txt_codigoUsuario.setEditable(true);
            lbl_nitTrabajador.setVisible(true);        
            txtF_nitParaTrabajador.setVisible(true);
            tipoDialogo=2;
        }
    }
    
    private void obtnerInfoIngresada(){
        datosUsuario[0]=txtF_Nombre.getText();
        datosUsuario[1]=txt_codigoUsuario.getText();
        datosUsuario[2]=txtF_Telefono.getText();
        if(lbl_tituloOperacion.getText().endsWith("CLIENTE")){            
            datosUsuario[4]=txtF_DPI.getText();
        }else{
            datosUsuario[3]=txtF_DPI.getText();
            datosUsuario[4]=txtF_nitParaTrabajador.getText();
        }//y así se resuleve el problema de los valores diferentes en el mismo espacio del arreglo xD
        datosUsuario[5]=FtxtF_Correo.getText();
        datosUsuario[6]=txtF_Direccion.getText();                        
    }
    
    private boolean revisarCamposObligatorios(){       
        
        if(txtF_Nombre.getText()==null){
            return false;
        }
        
        if(txtF_Telefono.getText()==null){
            return false;
        }
        
        if(lbl_tituloOperacion.getText().endsWith("EMPLEADO")){
            return revisarCamposObligatoriosTrabajadores();//si llega hasta aquí y devuelve true entonces todo en orden [cuando es empleado, sino sería con el return de abajito xD]                    
        }
        
        return true;
    }
    
    private boolean revisarCamposObligatoriosTrabajadores(){
        if(txtF_DPI.getText()==null){
            return false;
        }
        if(FtxtF_Correo.getText()==null){
            return false;
        }
        if(txtF_Direccion.getText()==null){
            return false;
        }
        
        return true;
    }   
    
    public void registrarUsuario(){//Este será el método empleado para la creación, a parte es para actualizar
        if(lbl_tituloOperacion.getText().endsWith("CLIENTE")){
            cajero.registrarDatosCliente(datosUsuario);
        }else{
            gerente.registrarDatosTrabajador(datosUsuario);
        }
    
    }
    
    public void actualizarUsuario(){
        if(lbl_tituloOperacion.getText().endsWith("CLIENTE")){
            
        }else{
           buscador.actualizarEmpleado(datosUsuario);
        }
    }
    
    
    
    
    //NO OLVIDES QUE ESTE MÉTODO SOLO SE ENCARGA DE REGISTRAR AL CLIENTE NO DE MANDAR 
    //AL LUGAR DE DONDE FUE LLAMADO ESTE MÉTODO, LOS VALORES QUE SOLICITAN
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtF_Correo;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_nitTrabajador;
    private javax.swing.JLabel lbl_tituloOperacion;
    private javax.swing.JTextField txtF_DPI;
    private javax.swing.JTextField txtF_Direccion;
    private javax.swing.JTextField txtF_Nombre;
    private javax.swing.JTextField txtF_Telefono;
    private javax.swing.JTextField txtF_nitParaTrabajador;
    private javax.swing.JTextField txt_codigoUsuario;
    // End of variables declaration//GEN-END:variables
}
