/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendTrabajadores;

/**
 *
 * @author phily
 */
public class nuevoProducto extends javax.swing.JFrame {

    /**
     * Creates new form nuevoProducto
     */
    public nuevoProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbl_tituloOperacion = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(718, 626));
        setPreferredSize(new java.awt.Dimension(718, 626));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel2.setText("CÓDIGO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 90, 20);

        jLabel3.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 90, 30);

        jLabel4.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel4.setText("CANTIDAD:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 280, 110, 30);

        jLabel5.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel5.setText("PRECIO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 240, 90, 30);

        jLabel6.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel6.setText("DESCRIPCIÓN:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 330, 140, 30);

        jLabel7.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel7.setText("GARANTÍA:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 560, 100, 30);

        jLabel9.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel9.setText("FABRICANTE:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 190, 120, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 90, 110, 28);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 140, 160, 28);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 190, 170, 28);
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(180, 280, 120, 28);
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(150, 240, 120, 28);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 380, 510, 160);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(160, 560, 110, 28);

        jButton1.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jButton1.setText("AGREGAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 620, 120, 50);

        lbl_tituloOperacion.setFont(new java.awt.Font("Sarai", 1, 33)); // NOI18N
        lbl_tituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloOperacion.setText("<<NUEVO PRODUCTO>>");
        getContentPane().add(lbl_tituloOperacion);
        lbl_tituloOperacion.setBounds(160, 20, 310, 40);

        lbl_Fondo.setBackground(new java.awt.Color(212, 175, 137));
        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-abstracto-geometrico-tonos-marrones_1095-35.jpg"))); // NOI18N
        lbl_Fondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_Fondo.setOpaque(true);
        getContentPane().add(lbl_Fondo);
        lbl_Fondo.setBounds(0, 0, 629, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void recibirTItulo(String tituloCOrrecto){
        lbl_tituloOperacion.setText(tituloCOrrecto);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_tituloOperacion;
    // End of variables declaration//GEN-END:variables
}
